/**
 * Equalizer APO Configuration Serializer
 * Converts structured data back to config.txt format
 */

/**
 * Serialize a full config object to APO config file format
 * @param {Object} config - Parsed config object
 * @returns {string} APO config file content
 */
export function serializeConfig(config) {
  const lines = [];

  // Header comment
  lines.push('# Equalizer APO Configuration');
  lines.push('# Generated by Neon Equalizer');
  lines.push('');

  // Device
  if (config.device && config.device !== 'all') {
    lines.push(`Device: ${config.device}`);
    lines.push('');
  }

  // Stage
  if (config.stage && config.stage !== 'post-mix') {
    lines.push(`Stage: ${config.stage}`);
    lines.push('');
  }

  // Channel
  if (config.channels && config.channels !== 'all') {
    lines.push(`Channel: ${config.channels}`);
    lines.push('');
  }

  // Include files
  if (config.includes && config.includes.length > 0) {
    for (const inc of config.includes) {
      if (inc.enabled) {
        lines.push(`Include: ${inc.file}`);
      } else {
        lines.push(`# Include: ${inc.file}`);
      }
    }
    lines.push('');
  }

  // Preamp
  if (config.preamp !== 0) {
    lines.push(`Preamp: ${config.preamp.toFixed(1)} dB`);
    lines.push('');
  }

  // Eval expressions
  if (config.evals && config.evals.length > 0) {
    for (const ev of config.evals) {
      lines.push(`Eval: ${ev.expr}`);
    }
    lines.push('');
  }

  // Conditionals
  if (config.conditionals && config.conditionals.length > 0) {
    for (const c of config.conditionals) {
      if (c.type === 'if') lines.push(`If: ${c.expr || ''}`);
      else if (c.type === 'elseif') lines.push(`ElseIf: ${c.expr || ''}`);
      else if (c.type === 'else') lines.push('Else:');
      else if (c.type === 'endif') lines.push('EndIf:');
    }
    lines.push('');
  }

  // Parametric EQ Filters
  if (config.filters && config.filters.length > 0) {
    lines.push('# Parametric EQ Filters');
    for (let i = 0; i < config.filters.length; i++) {
      lines.push(serializeFilter(config.filters[i], i + 1));
    }
    lines.push('');
  }

  // Graphic EQ
  if (
    config.graphicEQ &&
    config.graphicEQ.enabled &&
    config.graphicEQ.bands.length > 0 &&
    config.graphicEQ.bands.some(b => Math.abs(b.gain || 0) > 0.001)
  ) {
    lines.push('# Graphic EQ');
    const bandStrs = config.graphicEQ.bands.map(b =>
      `${b.frequency.toFixed(2)} ${b.gain.toFixed(2)}`
    );
    lines.push(`GraphicEQ: ${bandStrs.join('; ')}`);
    lines.push('');
  }

  // Convolution
  if (config.convolution && config.convolution.enabled && config.convolution.file) {
    lines.push('# Convolution');
    lines.push(`Convolution: ${config.convolution.file}`);
    lines.push('');
  }

  // Delays
  if (config.delays && config.delays.length > 0) {
    lines.push('# Delay');
    for (const delay of config.delays) {
      if (delay.enabled) {
        lines.push(serializeDelay(delay));
      }
    }
    lines.push('');
  }

  // Copy routes
  if (config.copies && config.copies.length > 0) {
    lines.push('# Channel Routing');
    const copyParts = config.copies
      .filter(c => c.enabled)
      .map(c => `${c.target}=${c.expression}`);
    if (copyParts.length > 0) {
      lines.push(`Copy: ${copyParts.join(' ')}`);
    }
    lines.push('');
  }

  // VST plugins
  const vstPlugins = (config.vstPlugins || []).filter(plugin => plugin.library || plugin.parameters);
  if (vstPlugins.length > 0) {
    lines.push('# VST Plugins');
    for (const plugin of vstPlugins) {
      const prefix = plugin.enabled === false ? '# ' : '';
      const params = plugin.parameters ? ` ${plugin.parameters.trim()}` : '';
      lines.push(`${prefix}VSTPlugin: Library ${quoteApoArg(plugin.library || '')}${params}`);
    }
    lines.push('');
  }

  // Loudness Correction
  if (config.loudnessCorrection) {
    const loudness = config.loudnessCorrection;
    lines.push('# Loudness Correction');
    lines.push(
      `LoudnessCorrection: State ${loudness.enabled === false ? 0 : 1}` +
      ` ReferenceLevel ${toApoInt(loudness.referenceLevel, 75)}` +
      ` ReferenceOffset ${toApoInt(loudness.referenceOffset, 0)}` +
      ` Attenuation ${formatApoNumber(clampNumber(loudness.attenuation, 0, 1, 1))}`
    );
    lines.push('');
  }

  // Preserve APO commands this UI does not yet edit directly instead of
  // silently dropping them on save.
  if (config.unsupportedLines && config.unsupportedLines.length > 0) {
    lines.push('# Preserved APO commands');
    for (const entry of config.unsupportedLines) {
      if (entry?.text) lines.push(entry.text);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Serialize a single filter to APO format
 */
function serializeFilter(filter, num) {
  const state = filter.enabled ? 'ON' : 'OFF';
  let parts = [`Filter: ${state} ${filter.type}`]; // Equalizer APO expects "Filter:" without a number

  // Frequency
  if (filter.frequency !== null && filter.frequency !== undefined) {
    parts.push(`Fc ${filter.frequency} Hz`);
  }

  // Gain
  if (filter.gain !== null && filter.gain !== undefined) {
    parts.push(`Gain ${filter.gain.toFixed(1)} dB`);
  }

  // Q or BW
  if (filter.q !== null && filter.q !== undefined) {
    parts.push(`Q ${filter.q.toFixed(3)}`);
  } else if (filter.bw !== null && filter.bw !== undefined) {
    parts.push(`BW Oct ${filter.bw.toFixed(3)}`);
  }

  // Modal T60
  if (filter.type === 'Modal' && filter.t60 !== null) {
    parts.push(`T60 target ${filter.t60} ms`);
  }

  // IIR custom coefficients
  if (filter.type === 'IIR' && filter.iirOrder !== null) {
    parts = [`Filter: ${state} IIR Order ${filter.iirOrder}`];
    if (filter.iirCoefficients) {
      parts.push(`Coefficients ${filter.iirCoefficients.join(' ')}`);
    }
  }

  return parts.join(' ');
}

/**
 * Serialize a delay value
 */
function serializeDelay(delay) {
  if (delay.unit === 'samples') {
    return `Delay: ${Math.round(delay.value)} samples`;
  }
  return `Delay: ${delay.value.toFixed(1)} ms`;
}

function quoteApoArg(value) {
  const str = String(value || '');
  if (!str) return '""';
  if (!/[\s"]/g.test(str)) return str;
  return `"${str.replace(/"/g, '""')}"`;
}

function toApoInt(value, fallback) {
  const num = Number(value);
  return Number.isFinite(num) ? Math.round(num) : fallback;
}

function clampNumber(value, min, max, fallback) {
  const num = Number(value);
  if (!Number.isFinite(num)) return fallback;
  return Math.min(max, Math.max(min, num));
}

function formatApoNumber(value) {
  return Number(value).toFixed(3).replace(/\.?0+$/, '');
}

/**
 * Create a default empty configuration
 */
export function createDefaultConfig() {
  return {
    device: null,
    channels: 'all',
    stage: 'post-mix',
    preamp: 0,
    filters: [],
    graphicEQ: null,
    convolution: null,
    delays: [],
    copies: [],
    vstPlugins: [],
    loudnessCorrection: null,
    includes: [],
    conditionals: [],
    evals: [],
    comments: [],
    unsupportedLines: [],
    rawLines: []
  };
}
